# Generated by Django 5.1.3 on 2024-12-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
