# Generated by Django 5.1.3 on 2024-12-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_network_app', '0003_remove_company_name_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='banner_image',
            field=models.ImageField(upload_to='static/company_banners/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='static/company_logos/'),
        ),
    ]
